version: "3.5"

services:
  kurki-db:
    image: truevoly/oracle-12c
    ports:
      - "8080:8080"
      - "1521:1521"
    volumes:
      - oracle_data:/u01/app/oracle
    container_name: kurki-db

  sis-kurki-integration:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    environment:
      KURKI_DB_USER: system
      KURKI_DB_PASSWORD: oracle
      KURKI_DB_CONNECTION_STRING: kurki-db:1521/xe
      KURKI_FALLBACK_KURSSI_OMISTAJA: DOE_J
    volumes:
      - ./:/usr/src/app
      - nodemodules:/usr/src/app/node_modules/
    container_name: sis-kurki-integration
    depends_on:
      - kurki-db

volumes:
  oracle_data:
  nodemodules:
