version: "3.5"

services:
  kurki-db:
    image: truevoly/oracle-12c
    ports:
      - "8080:8080"
      - "1521:1521"
    volumes:
      - ~/oracle_data/:/u01/app/oracle
    container_name: kurki-db

  sis-kurki-integration:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    container_name: sis-kurki-integration